apiVersion: v1
kind: Service
metadata:
  name: webappservice
spec:
  type: NodePort
  selector:
    app: webservice
  ports:
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8080
      targetPort: 8080
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 8080

---

apiVersion: v1
kind: Endpoints
metadata:
  name: database_endoint
subsets:
  - addresses:
      - ip: 127.0.0.1
    ports:
      - port: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webservice-deployment
  labels:
    app: webservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webservice
  template:
    metadata:
      labels:
        app: webservice
    spec:
      containers:
        - name: webservice
          image: etp:V1
          env:
            - name: DATABASE_URL
              value: "database_endoint.prod.svc.cluster.local:3306/Requestor"
            - name: DATABASE_USERNAME
              value: "Padraic"
            - name: DATABASE_PASSWORD
              value: "P@ssword123"
          ports:
            - containerPort: 3000